### ISSUE TITLE
JSON call fails when serving from https in Firefox 23

### ISSUE THREAD

**Issue by mchubby** [gileri/OSMTransportViewer#1]
Firefox 23 introduced breaking changes in the way mixed active content is allowed (cross-protocol).

refer to http://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire

You could replace the API call by
`
var api   = "//api.openstreetmap.fr/oapi/interpreter";
`
(notice the removed "http" protocol).
However, this modification leads to further issues:
- you might run into TLS CA-related issues for the api.openstreetmap.fr 3rd party
- you cannot load line.html from a file:// URI anymore

**Comment by gileri** [comment]
Hi, thanks for your bug report ! I didn't think this little project of mine would have been noticed right away.

I'll look into that soon. As you did guess, api.openstreetmap.fr doesn't use a trusted SSL CA, and it breaks XHRs in chrome either.
I think about adding a input/combobox to let users choose their Overpass API server which would default to overpass-api.de which have "clean" SSL.

**Comment by gileri** [comment]
Default to overpass-api.de server in https and allow user selection in ee83c5fa54d5107e6dbd290c4dcb493b67cf3b1f

Do you think it's the right way to do it ?

**Comment by mchubby** [comment]
I have no idea how it should be handled, and cannot really say I have an authoritative point of view on the matter.
I guess I can mark the issue as solved, anyways.
Thanks!
