### ISSUE TITLE
Blue markers

### ISSUE THREAD

**Issue by gosgtan** [gileri/OSMTransportViewer#13]
Hi, thanks for this renderer, I tested a lot, this is the best one. 

My question is, is there a way to remove blue markers from the view? They obstruct the map

Ty

**Comment by gileri** [comment]
Hi, thank you for the kind words @gosgtan !

The blue "teardrop" markers are the platforms mapped as a point on OSM. Do you suggest using another, less obtrusive icon, or a way to disable displaying platforms altogether ?

**Comment by gosgtan** [comment]
Hi, thanks for your response

Yes, a less obstrusive icon would do the trick I think, or giving the ability to hide platforms why not!

Keep up the good work :)

**Comment by gileri** [comment]
I used an existing icon I made for that, can you try it now ?

**Comment by gosgtan** [comment]
Way better!

Ty
