### ISSUE TITLE
Route not showing up

### ISSUE THREAD

**Issue by k1wiosm** [gileri/OSMTransportViewer#4]
I am trying to get a route but nothing is showing up. Maybe there is something wrong with the data on OpenStreetMap? 

This is the query that I am doing:
 https://gileri.github.io/OSMTransportViewer/?network=TUC+Pamplona&operator=TCC&ref=L15

Here is the route that should be showing up:
http://www.openstreetmap.org/relation/3205468#map=14/42.8000/-1.6758

**Comment by gileri** [comment]
This bus route is not part of a [route_master relation](https://wiki.openstreetmap.org/wiki/Relation:route_master), which group all route variants in the same relation. With these parameters, Overpass returns nothing, and so nothing will be displayed :)

I recon that the app is not really user-friendly, and will add soon an explanation of why data is not displayed when getting an error, or an empty response (a la Overpass-Turbo). Maybe also include stats in the sidebar like `2 variants found, 32 stops, 30 platforms`. 

The README is really outdated too, and does not explain the OSM data requirements in detail.

Also I always loaded the page in HTTP, I just noted with your links that my tile layer and Overpass query are loaded over HTTP.

So thank you for creating this issue, please keep it open as I adress these problems.

**Comment by gileri** [comment]
When no route_masters are found, a red bar is stating that (283b381d87c62f9c1a8de82de1b18b3c58f11bbb).

The README is now a bit more useful, but we're not there yet, and I still need to find a way to display route_master and route tags and informations.
