### ISSUE TITLE
Suggestion: Different color for stop_position & platform

### ISSUE THREAD

**Issue by k1wiosm** [gileri/OSMTransportViewer#6]
It would be nice if you could make the color of the markers different for `stop_position` and for `platform`.

**Comment by gileri** [comment]
Thank you for the suggestion :)

It should be better as of a31c2ecbdc9d8d873e0997ccd3c612ecc2da9666 and ae5ad4d91434fe2c3e8b10b65bd282902ae0be36

I made platforms purple (I have no taste :sweat_smile: ), and made a round icon for stops. Let me know what you think about them !

**Comment by k1wiosm** [comment]
I like the round icon for stops. I think it really makes sense.

I would suggest that you use the same color for platforms as areas and platforms as a node. (However there is no default purple marker :stuck_out_tongue_winking_eye: from Leaflet, so you would have to make your own)

**Comment by gileri** [comment]
I took a jab at it on 011f66b69e445d2d681c53a332758e1ac7bdcd1f.

**Comment by k1wiosm** [comment]
I like it.

**Comment by gileri** [comment]
Cool, i'm glad you like *it!

Thank you for your feedback !

(edit : typo)
